### PR TITLE
get_published_products

### PR DESCRIPTION
**Pull request by maabdelghaffar**
This PR includes:
- Adding get_published_products function to geoserver plugin. It returns a list of the published products under specific collection. 
- Adding is_product_published function to geoserver plugin. It returns True if product found already published, False if not found

### CODE REVIEW

**Comment by torse** [comment]
Nice. Would it be possible to also implement a "is_product_published" to check if a product with specific ID (e.g. S1B_IW_GRDH_1SDV_20171013T095250_20171013T095315_007809_00DCB4_7722) is already published? I am afraid that the get_published_products will get big over time (with hundereds/thousand new products each day..)

**Comment by maabdelghaffar** [comment]
Yes sure

**Comment by maabdelghaffar** [comment]
Yes log message updated and product_id will be included in the geoserver_rest_endpoint

**Comment by torse** [comment]
Ah, ok. I would have make the function explicit (..,collection_id,product_id) and building the url within instead of building the url outside the function. @randomorder: what do you think?

**Comment by randomorder** [comment]
@torse @maabdelghaffar I agree with @torse
One more thing:
Currently on error returns None. 
```
  elif r.status_code 	!= 200 and r.status_code != 404:
        log.info("Request failed")

```
I think it would be better to raise an exception and let the caller decide what to do. Take a look at what we do for the publishing function here:
https://github.com/geosolutions-it/evo-odas/blob/master/airflow/plugins/geoserver_plugin.py#L261

**Comment by randomorder** [comment]
Duplicated PR #270

**Pull request closed without merging**
